=== ibm-openbmc/openpower-hw-diags/analyzer/ras-data/schema/ras-data-schema-v02.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "RAS Data schema for openpower-hw-diags",
    "version": 2,
    "type": "object",
    "$defs": {
        "priority": {
            "type": "string",
            "enum": ["HIGH", "MED", "MED_A", "MED_B", "MED_C", "LOW"]
        },
        "flags": {
            "type": "string",
            "enum": [
                "sue_source",
                "sue_seen",
                "cs_possible",
                "external_checkstop",
                "recovered_error",
                "informational_only",
                "mnfg_informational_only",
                "mask_but_dont_clear",
                "crc_related_err",
                "crc_root_cause",
                "odp_data_corrupt_side_effect",
                "odp_data_corrupt_root_cause",
                "attn_from_ocmb"
            ]
        }
    },
    "additionalProperties": false,
    "required": ["model_ec", "version", "actions", "signatures"],
    "properties": {
        "model_ec": {
            "type": "string",
            "pattern": "^[0-9A-Fa-f]{8}$"
        },
        "version": {
            "type": "integer",
            "minimum": 2,
            "maximum": 2
        },
        "units": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^\\w+$": {
                    "type": "string",
                    "pattern": "^\\w+(\\/\\w+)*$"
                }
            }
        },
        "buses": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^\\w+$": {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["type"],
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": ["SMP_BUS", "OMI_BUS", "TBUS"]
                        },
                        "unit": {
                            "type": "string",
                            "pattern": "^\\w+$"
                        }
                    }
                }
            }
        },
        "actions": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^\\w+$": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": ["type"],
                        "properties": {
                            "type": {
                                "type": "string",
                                "enum": [
                                    "action",
                                    "callout_self",
                                    "callout_unit",
                                    "callout_connected",
                                    "callout_bus",
                                    "callout_clock",
                                    "callout_procedure",
                                    "callout_part",
                                    "plugin",
                                    "flag"
                                ]
                            },
                            "priority": {
                                "$ref": "#/$defs/priority"
                            },
                            "guard": {
                                "type": "boolean"
                            },
                            "name": {
                                "type": "string",
                                "pattern": "^\\w+$"
                            }
                        },
                        "allOf": [
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "action" }
                                    }
                                },
                                "then": {
                                    "required": ["name"],
                                    "not": { "required": ["priority", "guard"] }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_self" }
                                    }
                                },
                                "then": {
                                    "required": ["priority", "guard"],
                                    "not": { "required": ["name"] }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_unit" }
                                    }
                                },
                                "then": {
                                    "required": ["name", "priority", "guard"]
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_connected" }
                                    }
                                },
                                "then": {
                                    "required": ["name", "priority", "guard"]
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_bus" }
                                    }
                                },
                                "then": {
                                    "required": ["name", "priority", "guard"]
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_clock" }
                                    }
                                },
                                "then": {
                                    "required": ["name", "priority", "guard"],
                                    "properties": {
                                        "name": {
                                            "enum": [
                                                "OSC_REF_CLOCK_0",
                                                "OSC_REF_CLOCK_1",
                                                "TOD_CLOCK"
                                            ]
                                        }
                                    }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_procedure" }
                                    }
                                },
                                "then": {
                                    "required": ["name", "priority"],
                                    "not": { "required": ["guard"] },
                                    "properties": {
                                        "name": {
                                            "enum": ["LEVEL2", "SUE_SEEN"]
                                        }
                                    }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_part" }
                                    }
                                },
                                "then": {
                                    "required": ["name", "priority"],
                                    "not": { "required": ["guard"] },
                                    "properties": {
                                        "name": {
                                            "enum": ["PNOR"]
                                        }
                                    }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "plugin" }
                                    }
                                },
                                "then": {
                                    "required": ["name", "instance"],
                                    "not": {
                                        "required": ["priority", "guard"]
                                    },
                                    "properties": {
                                        "instance": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "flag" }
                                    }
                                },
                                "then": {
                                    "required": ["name"],
                                    "properties": {
                                        "name": {
                                            "$ref": "#/$defs/flags"
                                        }
                                    }
                                }
                            }
                        ]
                    }
                }
            }
        },
        "signatures": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[0-9A-Fa-f]{4}$": {
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": {
                        "^[0-9A-Fa-f]{2}$": {
                            "type": "object",
                            "additionalProperties": false,
                            "patternProperties": {
                                "^[0-9A-Fa-f]{2}$": {
                                    "type": "string",
                                    "pattern": "^\\w+$"
                                },
                                "flags": {
                                    "type": "array",
                                    "minItems": 1,
                                    "uniqueItems": true,
                                    "items": {
                                        "$ref": "#/$defs/flags"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== ibm-openbmc/openpower-hw-diags/analyzer/ras-data/data/ras-data-explorer-11.json
{
    "actions": {
        "dimm_H_mem_port_L_th1": [
            {
                "guard": true,
                "name": "dimm",
                "priority": "HIGH",
                "type": "callout_unit"
            },
            {
                "guard": false,
                "name": "mem_port",
                "priority": "LOW",
                "type": "callout_unit"
            },
            {
                "name": "th_1",
                "type": "action"
            }
        ],
        "dimm_H_mem_port_L_th_32perDay": [
            {
                "guard": true,
                "name": "dimm",
                "priority": "HIGH",
                "type": "callout_unit"
            },
            {
                "guard": false,
                "name": "mem_port",
                "priority": "LOW",
                "type": "callout_unit"
            },
            {
                "name": "th_32perDay",
                "type": "action"
            }
        ],
        "dimm_M": [
            {
                "guard": true,
                "name": "dimm",
                "priority": "MED",
                "type": "callout_unit"
            }
        ],
        "dimm_M_th1": [
            {
                "name": "dimm_M",
                "type": "action"
            },
            {
                "name": "th_1",
                "type": "action"
            }
        ],
        "downstream_attn": [
            {
                "name": "level2_M_th1",
                "type": "action"
            }
        ],
        "level2_M": [
            {
                "name": "LEVEL2",
                "priority": "MED",
                "type": "callout_procedure"
            }
        ],
        "level2_M_ocmb_L_th1": [
            {
                "name": "level2_M",
                "type": "action"
            },
            {
                "guard": false,
                "priority": "LOW",
                "type": "callout_self"
            },
            {
                "name": "th_1",
                "type": "action"
            }
        ],
        "level2_M_th1": [
            {
                "name": "level2_M",
                "type": "action"
            },
            {
                "name": "th_1",
                "type": "action"
            }
        ],
        "mainline_aue_iaue_handling": [
            {
                "name": "dimm_H_mem_port_L_th1",
                "type": "action"
            }
        ],
        "mainline_iue_handling": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ],
        "mainline_nce_tce_handling": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ],
        "mainline_ue_handling": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ],
        "maintenance_aue_handling": [
            {
                "name": "dimm_H_mem_port_L_th1",
                "type": "action"
            }
        ],
        "maintenance_iue_handling": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ],
        "mcbist_program_complete": [
            {
                "name": "level2_M_th1",
                "type": "action"
            }
        ],
        "mem_port_M": [
            {
                "guard": true,
                "name": "mem_port",
                "priority": "MED",
                "type": "callout_unit"
            }
        ],
        "mem_port_M_info_only": [
            {
                "name": "mem_port_M_th_32perDay",
                "type": "action"
            },
            {
                "name": "informational_only",
                "type": "flag"
            }
        ],
        "mem_port_M_th1": [
            {
                "name": "mem_port_M",
                "type": "action"
            },
            {
                "name": "th_1",
                "type": "action"
            }
        ],
        "mem_port_M_th_32perDay": [
            {
                "name": "mem_port_M",
                "type": "action"
            },
            {
                "name": "th_32perDay",
                "type": "action"
            }
        ],
        "memory_impe_handling": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ],
        "ocmb_H_omi_L_th1": [
            {
                "guard": true,
                "priority": "HIGH",
                "type": "callout_self"
            },
            {
                "guard": false,
                "name": "omi_bus",
                "priority": "LOW",
                "type": "callout_connected"
            },
            {
                "name": "th_1",
                "type": "action"
            }
        ],
        "ocmb_M": [
            {
                "guard": true,
                "priority": "MED",
                "type": "callout_self"
            }
        ],
        "ocmb_M_info_only": [
            {
                "name": "ocmb_M_th_32perDay",
                "type": "action"
            },
            {
                "name": "informational_only",
                "type": "flag"
            }
        ],
        "ocmb_M_th1": [
            {
                "name": "ocmb_M",
                "type": "action"
            },
            {
                "name": "th_1",
                "type": "action"
            }
        ],
        "ocmb_M_th_32perDay": [
            {
                "name": "ocmb_M",
                "type": "action"
            },
            {
                "name": "th_32perDay",
                "type": "action"
            }
        ],
        "omi_M": [
            {
                "guard": true,
                "name": "omi_bus",
                "priority": "MED",
                "type": "callout_connected"
            }
        ],
        "omi_M_th1": [
            {
                "name": "omi_M",
                "type": "action"
            },
            {
                "name": "th_1",
                "type": "action"
            }
        ],
        "omi_M_th_32perDay": [
            {
                "name": "omi_M",
                "type": "action"
            },
            {
                "name": "th_32perDay",
                "type": "action"
            }
        ],
        "omi_bus": [
            {
                "guard": true,
                "priority": "MED_A",
                "type": "callout_self"
            },
            {
                "guard": true,
                "name": "omi_bus",
                "priority": "MED_A",
                "type": "callout_connected"
            },
            {
                "guard": false,
                "name": "omi_bus",
                "priority": "LOW",
                "type": "callout_bus"
            }
        ],
        "omi_bus_info_only": [
            {
                "name": "omi_bus_th_32perDay",
                "type": "action"
            },
            {
                "name": "informational_only",
                "type": "flag"
            }
        ],
        "omi_bus_th1": [
            {
                "name": "omi_bus",
                "type": "action"
            },
            {
                "name": "th_1",
                "type": "action"
            }
        ],
        "omi_bus_th_32perDay": [
            {
                "name": "omi_bus",
                "type": "action"
            },
            {
                "name": "th_32perDay",
                "type": "action"
            }
        ],
        "omi_degraded_mode": [
            {
                "name": "omi_bus_th1",
                "type": "action"
            }
        ],
        "th_1": [],
        "th_32perDay": [
            {
                "name": "recovered_error",
                "type": "flag"
            }
        ],
        "verify_chip_mark_0": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ],
        "verify_chip_mark_1": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ],
        "verify_chip_mark_2": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ],
        "verify_chip_mark_3": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ],
        "verify_chip_mark_4": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ],
        "verify_chip_mark_5": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ],
        "verify_chip_mark_6": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ],
        "verify_chip_mark_7": [
            {
                "name": "dimm_M_th1",
                "type": "action"
            }
        ]
    },
    "buses": {
        "omi_bus": {
            "type": "OMI_BUS"
        }
    },
    "model_ec": "60d20011",
    "signatures": {
        "6401": {
            "00": {
                "00": "level2_M_th1"
            },
            "01": {
                "00": "ocmb_M_th1"
            },
            "02": {
                "00": "ocmb_M_th1",
                "flags": ["sue_source"]
            },
            "03": {
                "00": "ocmb_M_th1",
                "flags": ["sue_source"]
            },
            "04": {
                "00": "level2_M_th1"
            },
            "05": {
                "00": "level2_M_th1"
            },
            "06": {
                "00": "level2_M_th1"
            },
            "07": {
                "00": "level2_M_th1"
            },
            "08": {
                "00": "level2_M_th1"
